# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenSchemas
email: vsochat@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  OpenSchemas relies and extends from schema.org to generate specifications for open science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
logo: assets/images/logos/openschemas/logo_hexagon.png

# Alias
github_username:  openschemas
repo: https://github.com/openschemas/openschemas.github.io
name: OpenSchemas
twitter: containertools


# Build settings
markdown: kramdown

plugins:
 - jekyll-redirect-from
 - jekyll-sitemap

# Collections
collections:
  people:
    output: true
    permalink: /:collection/:path/
  groups:
    output: true
    permalink: /:collection/:path/
  useCases:
    output: true
    permalink: /:collection/:path/
  stories:
    output: true
